name: push

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: npm install --legacy-peer-deps
      - name: Test 🧪
        run: npm test
      - name: Vitest 🧪
        run: npm run vitest
  release:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install --legacy-peer-deps
      - name: Build 🚧
        run: npm run build
      - run: npm install -g npm@latest
      - uses: tobua/release-npm-action@v2
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
